### ISSUE TITLE
() Hello, i tried today to do some rdf with shadows but they are leaving party or either not coming in instance, toons i added are frost/blood specs dk and resto shaman but the dk is leaving the group only

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#128]
Hello, i tried today to do some rdf with shadows but they are leaving party or either not coming in instance, toons i added are frost/blood specs dk and resto shaman but the dk is leaving the group only

**Comment by Ye-Old-Potato** [comment]
I cannot do anything that makes them "leave the group" perse - That said - The mentioned issue regarding specs and roles are a bit janky so that can be confirmed. There is also existing jank regarding some follow mechanics of the bots which seem to be creating problems specifically during the fos pos and hor instances, mostly pertinent to the final portals to exit located in fos and pos - These portals are causing the bots to provide the "You're too far I will not follow" message even if you and your shadow port to the door of the entrance and are stacked upon each other, usually requiring a dismissal and re-call of the shadow.

Minor Addendum: QoL suggestion - Perhaps add an explicit "Do not eat" command that can prevent your bots from doing something as dumb as eating in the cave with the falling ice spikes in PoS causing them to get tossed all over the place and basically keep eating and re-eating while getting tossed every 1 second which basically is grossly inefficient and highly unavoidable outside of an explicit command to do that. But that's far from seriously important. 

Note: I've tried using follow, and other similar commands or functions that might cause them to interrupt their eating obsession, but it is simply impossible to pry them away from their improperly timed hunger.

**Comment by YggdrasilWotLK** [comment]
Let's make separate issue reports for separate issues please

Either way I think the issue this player had is solved by https://github.com/liyunfan1223/mod-playerbots/commit/ff5ad54f9164fbde1e42eb5438077e8379118396. Closing this issue, will reopen if issue reemerges.

In the meantime feel free to open separate reports for your other concerns
