### ISSUE TITLE
Death Comes From On High breaks Charm on Eye of Acherus early

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#144]
Hey, this Death Knight quest is bugging out, you interact with the quest objective, it starts moving the eye for you, and then it sends you back to your player. I have tried using the two different quest objectives, tried re logging, tried abandoning the quest and picking it back up again, any idea if i'm doing something wrong?

![image](https://github.com/user-attachments/assets/c4fd9505-35c4-4e83-8ee2-298c5dbfd723)

**Comment by Ye-Old-Potato** [comment]
I've not been able to recreate this bug outside of actively canceling the channel of that spell. Even hitting jump doesn't seem to actually do anything of that sort in my case, the only way it happens is if I literally drive myself out of the zone wherein you're supposed to be so further information might be required on this in order to address what's going on. 

At least that's my best understanding for the time being.

**Comment by YggdrasilWotLK** [comment]
I fixed this in https://github.com/YggdrasilWotLK/yggdrasilcore/commit/e81f900229a93b391680d62eeaf477bc56a6e7d3 yesterday, see Discord conversation for more information
