### ISSUE TITLE
() dried fruit and grunts waterskin should be x5 to that price not 1

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#19]
dried fruit and grunts waterskin should be x5 to that price not 1

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/5317371a-3a2c-45f7-a468-83a4789c057c)

**Comment by Ye-Old-Potato** [comment]
This issue seems to be differently stated on most databases as the per stack cost of each is attached here - However nowhere does it say a stack is supposed to be 5x units for either of those.

![Screenshot 2024-07-08 011145](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/174235943/e88ae4f2-a7ef-49e8-b993-b9c8e5f113ac)

**Comment by YggdrasilWotLK** [comment]
WoW-Head for TBC and WotLK classic actually reports 5x so we should
probably change it to that, @Lortz92  could you do this?
https://www.wowhead.com/wotlk/npc=17585/quartermaster-urgronn
