### ISSUE TITLE
Gerald Green NPC

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#33]
The NPC seems to be out of place, he should be standing behind the first set of NPC's with pitchforks and between other two quest givers. He is located in Farshire in Borean Tundra

![WoWScrnShot_071024_223915](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/74271882/07d4dc5a-b389-4a4e-bdea-ea0dfec446b1)

https://www.wowhead.com/wotlk/npc=26083/gerald-green
**Reproduction steps:** It seems like he get's back to his spot from time to time (probably at server restart), but the NPC goes out to fight Plagued Scavenger, if the player interacts with the NPC while he's fighting, he will stay in the place where the player interacted with him. He won't return back to his original spot after.

I recommend either somehow forcing him to come back afterwards (after some time delay) or making the player unable to interact with him when he's in combat

**Comment by YggdrasilWotLK** [comment]
We've looked into this, turns out he resets his home position at every interaction with him while in combat so he can progressively move farther and farther from his spawn point if interacted with in combat and start using the new area as his spawn point. Added a home position reset every time players enter the area, if he is too far away from original home
