### ISSUE TITLE
() https://www.wowhead.com/classic/quest=5624/garments-of-the-light it doesnt works. Heal and fortitude doesnt complete the quest

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#54]
https://www.wowhead.com/classic/quest=5624/garments-of-the-light it doesnt works. Heal and fortitude doesnt complete the quest

**Comment by Ye-Old-Potato** [comment]
Yeah, this is verified as an actual thing that happens - There is a need to, word for word, rank and every nuance included, do EXACTLY what the quest text explicitly states. Most players likely do not read this, so it is a decision whether we leave it as it stands for people to read the quests and follow the instructions given therein precisely verbatim, or we alter it to be eased out.

Current status: If the wrong spell ranks are used, or if the order of the spells used is not correctly done, it will not work.
If, however, you use the lower rank spells by choosing them specifically, it works just fine, and needs to be done in the correct order.

In the event that a player has rushed through and cast the spells provided in the wrong order, and immediately remedied that error with the correct rank and order, it will still not work since the NPC takes about 120 seconds or something like that, to reset and become "receptive" to the next player performing the quest action.

Proposed solutions:
Option 1: Simply leave it as it is, and let players read the quest text more carefully and adhere to it as per blizz-like intent.
Option 2: Just void the spell rank and order requirements entirely and allow players to literally faceroll or cheese the quest on instant basis.

**Comment by YggdrasilWotLK** [comment]
I think we should just leave the Lesser Heal rank part as is. (Side note: Even the top WoW Head comment specifies that players have to find and use the correct Lesse Heal spell rank.) Reading the directions of a quest is a pretty normal part of questing, after all. However: 

I think we're a little too fixed on the Lesser Heal (Rank 2) here. The quest text (and the top WoW Head comment) specifies that the quest requires Lesser Heal (Rank 2), which is correct, so we're not changing that part. But, the quest also requires Power Word: Fortitude (Rank 1 specifically). If the player uses Power Word: Fortitude (Rank 2) or higher (req. level 12), the quest won't complete for the next 30 minutes... There's no direction specifying that they need to find the lower rank Fortitude buff and use that instead of Rank 2. If we're changing anything it's the latter

**Comment by YggdrasilWotLK** [comment]
I've added "Power Word: Fortitude (Rank 1)" to the quest text of all these priest quests now, to clarify the requirement
