### ISSUE TITLE
() Not really a bug, but I do have to say that Nass makes a terrible companion .. not much kicking ass or name taking going on here ... at least not by him 😅  
Surely this cannot be right? I have not experienced this kind of companion slacking ever in game 😂
Edit: Nass takes quite a significant amount of damage each time, making it super easy for him to die.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#55]
Not really a bug, but I do have to say that Nass makes a terrible companion .. not much kicking ass or name taking going on here ... at least not by him 😅  
Surely this cannot be right? I have not experienced this kind of companion slacking ever in game 😂
Edit: Nass takes quite a significant amount of damage each time, making it super easy for him to die.

**Comment by Ye-Old-Potato** [comment]
Uhhh I mean this does not seem to happen as much as I can tell - I've not had this issue on the live server, and I have not been able to forcefully recreate it on the QA - So yeah. While Nass does die in a couple hits just like that, this seems to be quite similar to what it should be. And I mean in a way I can "force" it to artifically happen if i let Nass go fight stuff or get surrounded by enemies, but even then, it only seems to apply if you are an 80 or a sturdy class that decides to mass pull.

Digging around across the internet there isn't much evidence to suggest any such issues ever existing, since most players don't exactly try to get nass to tank stuff or fight, they usually just engage the fights themselves so there's usually never a need for such a thing to have existed.

With that said, however, there is evidence in later expansions for such a thing to have been implemented where he can actually do a full fight by himself but i really don't see why such a thing is or should be needed given that it's just a design part of the challenge to cover his "nass" and only really trigger him on dead bodies as much as I can tell. 

The evidence and testing seems to suggest there being no need for such a thing as "tankability" in this companion, so there's no bug perse.

To address the concern raised here however, outside of the intended functionality, if we wish to allow cheesability of this quest - We can potentially just either make Nass unattackable by the mobs to make him safe to them, immune to normal damage or just scale up his stats as they likely might have done in further expansions though we will need to alter his script since we likely  wouldn't be suited to incorporating future expansions' content here.

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/40d4f5a6-fe20-468e-b5b4-e801aec613bc)
https://www.wowhead.com/npc=28521/nass#comments:id=372622:reply=87147

![image](https://github.com/user-attachments/assets/277df61c-8bf8-444c-ae02-11bf06da8edc)
https://www.wowhead.com/wotlk/quest=12630/kickin-nass-and-takin-manes#comments

This is just fine, not a bug
