### ISSUE TITLE
(Zul'Drak Arena) victories are announcing the loser and not the winner.  where's our glory?!

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#70]
victories are announcing the loser and not the winner.  where's our glory?!

**Comment by YggdrasilWotLK** [comment]
From the Zul'Drak arena, @Lortz92 possible smart_scripts targeting issue? ![image](https://github.com/user-attachments/assets/b509e199-f119-44d8-ada2-9be9e3b59625)

**Comment by Ye-Old-Potato** [comment]
Well there's something odd here - the announcements are now entirely gone, at least the end of fight "yells" are missing entirely. They scream at start, nothing once the deed is done. Might need a revisit.

The end of all fights announcement of "rag tag team of nobodies" thing works, but the per fight announcement does not. Also, in the end, the player's name is not mentioned - afaik it's supposed to in the original 3.3.5a back in the day, current "classic" wotlk I cannot say however since I did not find any evidence.

**Comment by YggdrasilWotLK** [comment]
Temporarily ELUNA-d it until we can work out a solid smart script
