### ISSUE TITLE
Quest: A suitable disguise (QID: 20556)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#78]
Quest: A suitable disguise (QID: 20556)

Okay this cloth throwing roleplay/whatever it's called just does not happen, it's buggy and totally out of whack. It is supposed to work like the Sholazar fruit punch thing - but in this case, it simply doesn't work, try it out and you'll notice all the strangeness for instance the clothes tossed don't register, the timing is off, animations missing, and so on.

https://www.youtube.com/watch?v=eP2t0ao0He0

(Watch from 1:20 - 2:00 of this video that's all you really need for this purpose).

**Comment by YggdrasilWotLK** [comment]
We looked at this one about 2 months back (https://discord.com/channels/1214331197170258010/1253735567221461127/1253879801178095729).

I think this report is exaggerating a little, it's not a complete disaster, the main issue is just that the dialogues are in the wrong order. And if he can't be interacted with it's because he has already put the bag with the tabard on the ground, or the player threw the wrong item too many times and he's on cooldown for a minute or two. Laundry is hard work and the poor guy needs rest every now and then.

Order mix-up: 
When he asks for water, he wants shirts. When he asks for unmentionables, he wants water. When he asks for shirts, he wants unmentionables. 

AzerothCore thread: https://github.com/azerothcore/azerothcore-wotlk/issues/744#issuecomment-2188530923

I've put the dialogue order change up on QA if you would like to have a crack at it.
